[package]
name = "bevy_draped_lines"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = { version = "0.5.0", git = "https://github.com/bevyengine/bevy.git", branch = "main" }
bytemuck = "1.5.1"
